const state={token:sessionStorage.getItem('sf_admin_token')||'',device:localStorage.getItem('sf_admin_device')||crypto.randomUUID(),tab:'dashboard'};
localStorage.setItem('sf_admin_device',state.device);
const tabs=[['dashboard','看板'],['config','配置'],['announcements','公告'],['users','用户'],['reports','举报'],['deletions','注销'],['complaints','版权投诉'],['devices','设备'],['orders','订单'],['plans','套餐'],['codes','卡密'],['bot','Bot'],['audit','审计']];
const $=id=>document.getElementById(id);const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const headers={'Content-Type':'application/json','X-Device-ID':state.device,'X-Device-Name':'Admin Web','X-Device-Platform':'web-admin',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});const body=await response.json().catch(()=>({msg:'Invalid server response'}));if(!response.ok||body.code!==0)throw new Error(body.msg||`HTTP ${response.status}`);return body.data||{};}
function notify(message,error=false){$('notice').textContent=message;$('notice').className=error?'error':'notice'}
async function login(){try{const data=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});state.token=data.access_token;sessionStorage.setItem('sf_admin_token',state.token);await start()}catch(error){$('loginError').textContent=error.message}}
function logout(){sessionStorage.removeItem('sf_admin_token');location.reload()}
async function start(){$('login').hidden=true;$('console').hidden=false;$('logout').hidden=false;renderTabs();await loadTab()}
function renderTabs(){$('tabs').innerHTML=tabs.map(([id,label])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}">${label}</button>`).join('');$('tabs').querySelectorAll('button').forEach(button=>button.onclick=()=>{state.tab=button.dataset.tab;renderTabs();loadTab()})}
async function loadTab(){notify('');$('content').innerHTML='<p>加载中…</p>';try{await ({dashboard,config,announcements,users,reports,deletions,complaints,devices,orders,plans,codes,bot,audit}[state.tab]||dashboard)()}catch(error){$('content').innerHTML=`<p class="error">${esc(error.message)}</p>`}}
async function dashboard(){const d=await api('/api/v1/admin/dashboard');const labels={users:'用户',verified_users:'已验证',active_vip_users:'有效会员',rooms:'房间',active_rooms:'活跃房间',couples:'情侣',pending_reports:'待审举报',activated_orders:'已激活订单',revenue_minor:'收入（分）',reviews:'影评',together_watchings:'共同观看'};$('content').innerHTML=`<h2>运营看板</h2><div class="grid">${Object.entries(labels).map(([key,label])=>`<div class="metric">${label}<strong>${esc(d[key])}</strong></div>`).join('')}</div>`}
async function config(){const d=await api('/api/v1/admin/config');$('content').innerHTML=`<h2>运行配置</h2><label><input class="toggle" id="maintenance" type="checkbox" ${d.maintenance.enabled?'checked':''}> 维护模式</label><label>维护提示<input id="maintenanceMessage" value="${esc(d.maintenance.message)}"></label><label>全局公告<textarea id="globalAnnouncement">${esc(d.branding.global_announcement)}</textarea></label><label>功能位（JSON）<textarea id="features">${esc(JSON.stringify(d.features,null,2))}</textarea></label><button id="saveConfig" class="danger">确认并更新配置</button>`;$('saveConfig').onclick=async()=>{if(!confirm('配置会立即影响所有用户，确认更新？'))return;try{await api('/api/v1/admin/config',{method:'PUT',headers:{'X-Confirm-Dangerous':'update-runtime-config'},body:JSON.stringify({maintenance:{enabled:$('maintenance').checked,message:$('maintenanceMessage').value},branding:{global_announcement:$('globalAnnouncement').value,startup_announcement_id:0},features:JSON.parse($('features').value)})});notify('配置已更新');await config()}catch(error){notify(error.message,true)}}}
async function announcements(){const d=await api('/api/v1/admin/announcements');$('content').innerHTML=`<h2>公告</h2><div class="row"><label>标题<input id="aTitle"></label><label>类型<select id="aKind"><option value="list">列表</option><option value="startup">启动弹窗</option><option value="room">房间实时</option></select></label></div><label>内容<textarea id="aBody"></textarea></label><button id="createAnnouncement">发布</button><div>${d.announcements.map(a=>`<div class="item"><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p><span class="muted">${esc(a.kind)}</span> <button class="danger deleteA" data-id="${a.id}">删除</button></div>`).join('')}</div>`;$('createAnnouncement').onclick=()=>mutate('/api/v1/admin/announcements','POST',{title:$('aTitle').value,body:$('aBody').value,kind:$('aKind').value,active:true},announcements);document.querySelectorAll('.deleteA').forEach(b=>b.onclick=()=>mutate(`/api/v1/admin/announcements/${b.dataset.id}`,'DELETE',null,announcements))}
async function users(){const q=new URLSearchParams(location.hash.slice(1)).get('q')||'';const d=await api(`/api/v1/admin/users?q=${encodeURIComponent(q)}`);$('content').innerHTML=`<h2>用户</h2><div class="row"><label>搜索<input id="userQuery" value="${esc(q)}"></label><button id="searchUsers">搜索</button></div>${d.users.map(u=>`<div class="item"><h3>${esc(u.display_name)} <span class="muted">${esc(u.email)}</span></h3><div class="row"><label>角色<select class="role" data-id="${esc(u.id)}">${['','super_admin','admin','operator','seller'].map(role=>`<option ${u.admin_role===role?'selected':''}>${role}</option>`).join('')}</select></label><label>增加会员天数<input class="vipDays" data-id="${esc(u.id)}" type="number" min="1"></label><button class="saveUser" data-id="${esc(u.id)}">保存</button></div></div>`).join('')}`;$('searchUsers').onclick=()=>{location.hash=`q=${encodeURIComponent($('userQuery').value)}`;users()};document.querySelectorAll('.saveUser').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,role=document.querySelector(`.role[data-id="${CSS.escape(id)}"]`).value,days=Number(document.querySelector(`.vipDays[data-id="${CSS.escape(id)}"]`).value||0);try{await api(`/api/v1/admin/users/${encodeURIComponent(id)}/role`,{method:'PUT',body:JSON.stringify({role})});if(days>0)await api(`/api/v1/admin/users/${encodeURIComponent(id)}/vip`,{method:'PUT',body:JSON.stringify({days})});notify('用户已更新')}catch(error){notify(error.message,true)}})}
async function reports(){const d=await api('/api/v1/admin/reports?status=pending');$('content').innerHTML=`<h2>待审举报</h2>${d.reports.map(r=>`<div class="item"><h3>${esc(r.reason)} · ${esc(r.target_type)} ${esc(r.target_id)}</h3><p>${esc(r.details)}</p><button class="resolve" data-id="${r.id}" data-status="actioned">处理</button> <button class="resolve secondary" data-id="${r.id}" data-status="dismissed">驳回</button></div>`).join('')||'<p>暂无</p>'}`;document.querySelectorAll('.resolve').forEach(b=>b.onclick=()=>mutate(`/api/v1/admin/reports/${b.dataset.id}/resolve`,'POST',{status:b.dataset.status,resolution:'管理后台处理'},reports))}
async function deletions(){const d=await api('/api/v1/admin/account-deletions?status=pending');$('content').innerHTML=`<h2>账号注销审核</h2>${d.requests.map(v=>`<div class="item"><h3>申请 #${v.id}</h3><p>${esc(v.reason)}</p><button class="approveDeletion danger" data-id="${v.id}">不可逆批准</button> <button class="rejectDeletion secondary" data-id="${v.id}">驳回</button></div>`).join('')||'<p>暂无待审申请</p>'}`;document.querySelectorAll('.approveDeletion').forEach(b=>b.onclick=()=>{if(confirm('将不可逆删除账号及关联数据，确认？'))mutate(`/api/v1/admin/account-deletions/${b.dataset.id}/resolve`,'POST',{approve:true,resolution:'身份及申请已核验',confirm:'IRREVERSIBLY DELETE ACCOUNT'},deletions)});document.querySelectorAll('.rejectDeletion').forEach(b=>b.onclick=()=>mutate(`/api/v1/admin/account-deletions/${b.dataset.id}/resolve`,'POST',{approve:false,resolution:'申请未通过核验'},deletions))}
async function complaints(){const d=await api('/api/v1/admin/copyright-complaints');$('content').innerHTML=`<h2>版权投诉</h2>${d.complaints.map(v=>`<div class="item"><h3>#${v.id} · ${esc(v.status)} · 截止 ${new Date(v.due_at).toLocaleString()}</h3><p><b>${esc(v.claimant_name)}</b> ${esc(v.claimant_email)}</p><p>${esc(v.rights_basis)}</p><p><a href="${esc(v.infringement_url)}" target="_blank" rel="noreferrer">侵权链接</a> · 房间 ${esc(v.room_code||'-')}</p><pre>${esc((v.evidence||[]).join('\n'))}</pre><button class="actionComplaint danger" data-id="${v.id}" data-room="${esc(v.room_code||'')}">下架处理</button> <button class="rejectComplaint secondary" data-id="${v.id}">驳回</button></div>`).join('')||'<p>暂无投诉</p>'}`;document.querySelectorAll('.actionComplaint').forEach(b=>b.onclick=()=>mutate(`/api/v1/admin/copyright-complaints/${b.dataset.id}/resolve`,'POST',{status:'actioned',resolution:'权属核验后下架',close_room:Boolean(b.dataset.room)},complaints));document.querySelectorAll('.rejectComplaint').forEach(b=>b.onclick=()=>mutate(`/api/v1/admin/copyright-complaints/${b.dataset.id}/resolve`,'POST',{status:'rejected',resolution:'证据不足',close_room:false},complaints))}
async function devices(){const d=await api('/api/v1/admin/device-bans');$('content').innerHTML=`<h2>设备封禁</h2>${d.bans.map(b=>`<div class="item"><code>${esc(b.device_hash)}</code><p>${esc(b.reason)}</p><button class="unban" data-hash="${esc(b.device_hash)}">解封</button></div>`).join('')||'<p>暂无封禁</p>'}`;document.querySelectorAll('.unban').forEach(b=>b.onclick=()=>mutate(`/api/v1/admin/device-bans/${b.dataset.hash}`,'DELETE',null,devices))}
async function orders(){const d=await api('/api/v1/admin/orders');$('content').innerHTML=`<h2>订单</h2>${d.orders.map(o=>`<div class="item"><h3>${esc(o.order_no)} · ${esc(o.status)}</h3><p>${esc(o.plan_title)} / ¥${(o.amount_minor/100).toFixed(2)}</p>${o.status!=='activated'?`<button class="activate" data-id="${esc(o.order_no)}">人工补单</button>`:''}</div>`).join('')||'<p>暂无订单</p>'}`;document.querySelectorAll('.activate').forEach(b=>b.onclick=()=>mutate(`/api/v1/admin/orders/${b.dataset.id}/activate`,'POST',{},orders))}
async function plans(){const d=await api('/api/v1/admin/plans');$('content').innerHTML=`<h2>会员套餐</h2>${d.plans.map(p=>`<div class="item"><h3>${esc(p.title)}</h3><div class="row"><label>价格（分）<input class="price" data-id="${p.id}" type="number" value="${p.price_minor}"></label><label>天数<input class="duration" data-id="${p.id}" type="number" value="${p.duration_days}"></label><label><input class="enabled toggle" data-id="${p.id}" type="checkbox" ${p.enabled?'checked':''}> 上架</label><button class="savePlan" data-id="${p.id}">保存</button></div></div>`).join('')}`;document.querySelectorAll('.savePlan').forEach(b=>b.onclick=()=>{const p=d.plans.find(x=>x.id===b.dataset.id);p.price_minor=Number(document.querySelector(`.price[data-id="${p.id}"]`).value);p.duration_days=Number(document.querySelector(`.duration[data-id="${p.id}"]`).value);p.enabled=document.querySelector(`.enabled[data-id="${p.id}"]`).checked;mutate(`/api/v1/admin/plans/${p.id}`,'PUT',p,plans)})}
async function codes(){$('content').innerHTML='<h2>激活码批次</h2><div class="row"><label>套餐 ID<input id="codePlan" value="monthly"></label><label>数量<input id="codeCount" type="number" min="1" max="100" value="10"></label><button id="createCodes">生成</button></div><pre id="codeOutput">明文只显示一次，请安全导出。</pre>';$('createCodes').onclick=async()=>{try{const d=await api('/api/v1/admin/activation-codes',{method:'POST',body:JSON.stringify({plan_id:$('codePlan').value,count:Number($('codeCount').value)})});$('codeOutput').textContent=d.codes.map(c=>c.code).join('\n')}catch(error){notify(error.message,true)}}}
async function bot(){const d=await api('/api/v1/admin/room-bot');$('content').innerHTML=`<h2>房间 Bot</h2><label><input id="botEnabled" class="toggle" type="checkbox" ${d.enabled?'checked':''}> 启用</label><label>名称<input id="botName" value="${esc(d.display_name)}"></label><div class="row"><label>召唤策略<select id="summon">${['admin','vip','allowlist','all'].map(v=>`<option ${d.summon_policy===v?'selected':''}>${v}</option>`).join('')}</select></label><label>回复策略<select id="reply">${['mention','all','off'].map(v=>`<option ${d.reply_policy===v?'selected':''}>${v}</option>`).join('')}</select></label></div><label>提供商 HTTPS URL<input id="botUrl" value="${esc(d.provider_base_url)}"></label><label>模型<input id="botModel" value="${esc(d.model)}"></label><label>新密钥（留空不修改）<input id="botCredential" type="password" placeholder="${d.has_credential?'已配置':'未配置'}"></label><button id="saveBot">保存</button>`;$('saveBot').onclick=()=>mutate('/api/v1/admin/room-bot','PUT',{enabled:$('botEnabled').checked,display_name:$('botName').value,summon_policy:$('summon').value,reply_policy:$('reply').value,provider_base_url:$('botUrl').value,model:$('botModel').value,credential:$('botCredential').value},bot)}
async function audit(){const d=await api('/api/v1/admin/audit');$('content').innerHTML=`<h2>审计链 · ${d.chain_valid?'有效':'异常'}</h2><pre>${esc(JSON.stringify(d.events,null,2))}</pre>`}
async function mutate(path,method,body,reload){try{await api(path,{method,body:body===null?undefined:JSON.stringify(body)});notify('操作成功');if(reload)await reload()}catch(error){notify(error.message,true)}}
$('loginButton').onclick=login;$('password').onkeydown=e=>{if(e.key==='Enter')login()};$('logout').onclick=logout;if(state.token)start();
